// Standalone fixture runner for environments that cannot launch Playwright.
// Test-only adapters map localhost URLs to LinkedIn and mock Chrome storage.
import http from 'node:http';
import { readFileSync } from 'node:fs';
const read = name => readFileSync(new URL(`../extension/${name}`, import.meta.url),'utf8');
const card = (who,id,extra='') => `<article class="feed-shared-update-v2" id="${id}"><div class="update-components-actor"><a class="update-components-actor__meta-link" href="https://www.linkedin.com/in/${who}/">${who}</a></div><p>My post about making space for focused work.</p>${extra}<p id="comment-${id}">A thoughtful reply from a reader.</p><div contenteditable="true" role="textbox">Reply here</div></article>`;
const runner = `<!doctype html><html><head><title>LinkedIn Quiet browser checks</title></head><body style="font:16px system-ui;margin:40px"><h1>LinkedIn Quiet browser checks</h1><p id="summary">Running…</p><ol id="results"></ol><iframe title="Extension fixture" style="width:100%;height:600px;border:1px solid #ddd"></iframe><script>
const frame=document.querySelector('iframe');let pass=0,fail=0;
const tick=()=>new Promise(r=>setTimeout(r,120));
async function load(path,kind='posts',slug='example'){frame.src=path+(path.includes('?')?'&':'?')+'kind='+kind+'&slug='+slug;await new Promise(r=>frame.onload=r);await tick();return frame.contentDocument;}
function visible(d,s){const el=d.querySelector(s);return !!el&&d.defaultView.getComputedStyle(el).visibility==='visible'&&el.getClientRects().length>0;}
function check(value,message){if(!value)throw Error(message);}
async function test(name,fn){const li=document.createElement('li');try{await fn();pass++;li.textContent='PASS — '+name;}catch(e){fail++;li.textContent='FAIL — '+name+': '+e.message;}document.querySelector('#results').append(li);}
(async()=>{
await test('Feed stays masked, including own posts',async()=>{const d=await load('/feed/');check(!visible(d,'#own'),'own post leaked');check(!visible(d,'#inbox'),'inbox leaked');});
await test('Own posts and comments visible; other posts hidden',async()=>{const d=await load('/in/example/recent-activity/shares/');check(visible(d,'#own'),'own post missing');check(visible(d,'#comment-own'),'comment missing');check(!visible(d,'#other'),'other post leaked');});
await test('Direct post links verify the author',async()=>{const d=await load('/feed/update/urn:li:activity:123/');check(visible(d,'#own'),'own post missing');check(!visible(d,'#other'),'other leaked');});
await test('Embedded own post cannot reveal an outer repost',async()=>{const d=await load('/in/example/recent-activity/all/','nested');check(!visible(d,'#outer'),'outer leaked');check(!visible(d,'#nested'),'nested leaked');});
await test('Own profile visible; recommendations hidden',async()=>{const d=await load('/in/example/','profile');check(visible(d,'#experience'),'profile missing');check(!visible(d,'#interests'),'interests leaked');check(!visible(d,'aside'),'sidebar leaked');});
await test('Stale profile identity stays masked',async()=>{const d=await load('/in/example/','wrong-profile');check(!visible(d,'#experience'),'stale profile leaked');});
await test('Recycled cards lose ownership immediately',async()=>{const d=await load('/in/example/recent-activity/shares/');d.querySelector('#own a').href='https://www.linkedin.com/in/other/';await tick();check(!visible(d,'#own'),'recycled post leaked');});
await test('SPA navigation revokes approved content',async()=>{const d=await load('/in/example/recent-activity/shares/');d.defaultView.history.pushState({},'','/messaging/');await tick();check(!visible(d,'#own'),'navigation leaked');});
await test('Changing settings revokes old access',async()=>{const d=await load('/in/example/recent-activity/shares/');await d.defaultView.chrome.storage.local.set({profileSlug:'someone'});await tick();check(!visible(d,'#own'),'old profile leaked');});
await test('Unconfigured extension masks everything',async()=>{const d=await load('/feed/','posts','');check(!visible(d,'#own'),'setup leaked');});
await test('Authentication works and masks again when leaving',async()=>{const d=await load('/login');check(visible(d,'#own'),'login hidden');d.defaultView.history.pushState({},'','/feed/');await tick();check(!visible(d,'#own'),'auth exit leaked');});
await test('Default CSS works without JavaScript',async()=>{const d=await load('/feed/','css');check(!visible(d,'#own'),'CSS failed');});
await test('Composer works while feed, inbox, and unrelated dialogs stay hidden',async()=>{const d=await load('/feed/?shareActive=true','composer');check(visible(d,'#editor'),'composer hidden');check(!visible(d,'#own'),'feed leaked');check(!visible(d,'#inbox'),'inbox leaked');check(!visible(d,'#other-dialog'),'unrelated dialog leaked');d.querySelector('#editor').focus();d.querySelector('#editor').textContent='A new post draft';await tick();check(d.activeElement===d.querySelector('#editor'),'editor lost focus');check(visible(d,'#publish'),'Post button hidden');d.querySelector('#publish').click();await tick();check(d.body.dataset.submitted==='yes','native post action did not run');check(!visible(d,'#own'),'feed leaked after posting');});
await test('Native Start a post fallback stays usable',async()=>{const d=await load('/feed/?shareActive=true','start');check(visible(d,'#editor'),'native start control was not opened');check(!visible(d,'#own'),'feed leaked');d.querySelector('#cancel').click();await tick();check(visible(d,'#start-post'),'fallback hidden after closing');d.querySelector('#start-post').click();await tick();check(visible(d,'#editor'),'fallback did not reopen composer');});
await test('Composer survives LinkedIn clearing the share URL',async()=>{const d=await load('/feed/?shareActive=true','composer');d.defaultView.history.replaceState({},'','/feed/');await tick();check(visible(d,'#editor'),'composer lost after URL cleanup');check(!visible(d,'#own'),'feed leaked');});
await test('Cancel closes composer without exposing the feed',async()=>{const d=await load('/feed/?shareActive=true','composer');d.querySelector('#cancel').click();await tick();check(!visible(d,'#editor'),'composer stayed open');check(!visible(d,'#own'),'feed leaked');});
await test('Loading sentinel has geometry and can load the first post',async()=>{const d=await load('/in/example/recent-activity/shares/','loading');await tick();check(d.querySelector('#sentinel').getBoundingClientRect().height>0,'sentinel collapsed');check(visible(d,'#loaded'),'IntersectionObserver did not load post');check(!visible(d,'#sentinel'),'sentinel text leaked');});
await test('Load more control remains usable with posts masked',async()=>{const d=await load('/in/example/recent-activity/shares/','load-more');check(visible(d,'#load-more'),'load-more hidden');d.querySelector('#load-more').click();await tick();check(visible(d,'#loaded'),'next page did not appear');});
await test('Missing author retains geometry but stays invisible',async()=>{const d=await load('/in/example/recent-activity/shares/','pending');check(d.querySelector('#pending').getBoundingClientRect().height>0,'pending collapsed');check(!visible(d,'#pending'),'pending leaked');d.querySelector('#pending').insertAdjacentHTML('afterbegin','<div class="update-components-actor"><a class="update-components-actor__meta-link" href="https://www.linkedin.com/in/example/">example</a></div>');await tick();check(visible(d,'#pending'),'post not revealed after author arrives');});
await test('Only changed posts are rechecked in a 100-post page',async()=>{const d=await load('/in/example/recent-activity/shares/','many');const w=d.defaultView;w.actorChecks=0;d.querySelector('#noise').className='changed';await tick();check(w.actorChecks===0,'unrelated mutation rechecked '+w.actorChecks+' posts');d.querySelector('#p50 a').href='https://www.linkedin.com/in/other/';await tick();check(w.actorChecks===1,'one author edit rechecked '+w.actorChecks+' posts');check(!visible(d,'#p50'),'changed owner leaked');check(visible(d,'#p49'),'unchanged post hidden');});
await test('Comment drafts keep focus during incremental updates',async()=>{const d=await load('/in/example/recent-activity/shares/');const editor=d.querySelector('#own [contenteditable]');editor.focus();editor.textContent='My reply draft';await tick();check(d.activeElement===editor,'comment editor lost focus');check(visible(d,'#own'),'own post disappeared');});
await test('Generated-class native composer and its footer are visible',async()=>{const d=await load('/feed/?shareActive=true','modern');check(visible(d,'#editor'),'new editor hidden');check(visible(d,'#publish'),'native footer hidden');check(!visible(d,'#other-dialog'),'message dialog leaked');check(!visible(d,'#own'),'feed leaked');});
await test('Start a post opens automatically without legacy class names',async()=>{const d=await load('/feed/?shareActive=true','modern-start');check(visible(d,'#editor'),'semantic native trigger failed');check(visible(d,'#publish'),'Post control hidden');check(!visible(d,'#own'),'feed leaked');d.querySelector('#cancel').click();await tick();await new Promise(r=>setTimeout(r,850));check(!visible(d,'#editor'),'cancelled editor reopened');});
await test('Hidden cached dialogs no longer count as open composers',async()=>{const d=await load('/feed/?shareActive=true','modern');const dialog=d.querySelector('#editor').closest('[role=dialog]');dialog.hidden=true;await tick();check(!dialog.hasAttribute('data-lq-composer'),'closed dialog still approved');check(!visible(d,'#own'),'feed leaked');});
document.querySelector('#summary').textContent=pass+' passed, '+fail+' failed';document.title=pass+' passed, '+fail+' failed — LinkedIn Quiet';await load('/feed/');
})();</script></body></html>`;
const server = http.createServer((req,res)=>{
  const url = new URL(req.url,'http://localhost:8765');
  res.setHeader('Content-Type','text/html; charset=utf-8');
  if(url.pathname==='/'){res.end(runner);return;}
  const kind=url.searchParams.get('kind');
  const slug=url.searchParams.get('slug');
  let content=card('example','own')+card('someone','other','<a href="https://www.linkedin.com/in/example/">Mention of me</a>');
  if(kind==='nested')content=card('someone','outer',card('example','nested'));
  if(kind==='profile'||kind==='wrong-profile')content=`<section class="pv-top-card"><a href="https://www.linkedin.com/in/${kind==='profile'?'example':'someone'}/overlay/photo/">Profile photo</a><h1>Example Person</h1></section><section id="experience">My work and experience</section><section><div id="interests">Recommendations</div></section>`;
  const composer=`<div class="artdeco-modal share-box-v2__modal" role="dialog" style="background:white;padding:30px;margin:20px"><h2>Create a post</h2><div id="editor" contenteditable="true" role="textbox" aria-label="Write a post" style="min-height:100px;border:1px solid #aaa;padding:16px"></div><button id="publish" onclick="document.body.dataset.submitted='yes';this.closest('[role=dialog]').remove()">Post</button><button id="cancel" onclick="this.closest('[role=dialog]').remove()">Cancel</button></div>`;
  const modern=composer.replace('artdeco-modal share-box-v2__modal','generated-abc123').replace('<button id="publish"','<footer><button id="publish"').replace('>Cancel</button></div>', '>Cancel</button></footer></div>');
  let after='';
  if(kind==='modern')after=modern+'<div role="dialog" id="other-dialog"><div role="textbox" contenteditable="true">Private message</div><button>Send</button></div>';
  if(kind==='modern-start')content+='<button id="start-post" class="generated-abc123"><span>Start a post</span></button>';
  if(kind==='composer')after=composer+'<div role="dialog" id="other-dialog">Private message dialog</div>';
  if(kind==='start')content+='<button id="start-post" class="share-box-feed-entry__trigger">Start a post</button>';
  if(kind==='loading')content='<div id="sentinel" style="height:20px">Loading hidden text</div>';
  if(kind==='load-more')content='<button id="load-more" class="scaffold-finite-scroll__load-button">Load more posts</button>';
  if(kind==='pending')content='<article id="pending" class="feed-shared-update-v2" style="height:120px">Awaiting author</article>';
  if(kind==='many')content=Array.from({length:100},(_,i)=>card('example','p'+i)).join('')+'<span id="noise">Hidden noise</span>';
  const fixtureScript=kind==='modern-start'?`document.querySelector('#start-post').onclick=()=>document.body.insertAdjacentHTML('beforeend',${JSON.stringify(modern)});`:kind==='start'?`document.querySelector('#start-post').onclick=()=>document.body.insertAdjacentHTML('beforeend',${JSON.stringify(composer)});`:kind==='loading'?`new IntersectionObserver((entries,observer)=>{if(entries.some(e=>e.isIntersecting)){document.querySelector('main').insertAdjacentHTML('afterbegin',${JSON.stringify(card('example','loaded'))});observer.disconnect();}}).observe(document.querySelector('#sentinel'));`:kind==='load-more'?`document.querySelector('#load-more').onclick=()=>document.querySelector('main').insertAdjacentHTML('afterbegin',${JSON.stringify(card('example','loaded'))});`:'';
  const shim=`const originalPolicy=LinkedInQuietPolicy;const map=v=>String(v).replace(location.origin,'https://www.linkedin.com');window.LinkedInQuietPolicy={profileSlug:v=>originalPolicy.profileSlug(map(v)),route:(v,s)=>originalPolicy.route(map(v),s)};window.actorChecks=0;const originalQSA=Element.prototype.querySelectorAll;Element.prototype.querySelectorAll=function(selector){if(selector.startsWith('.update-components-actor__meta-link'))window.actorChecks++;return originalQSA.call(this,selector);};window.listeners=[];window.savedSlug=${JSON.stringify(slug)};window.chrome={storage:{local:{get:async()=>({profileSlug:savedSlug}),set:async v=>{savedSlug=v.profileSlug;listeners.forEach(fn=>fn({profileSlug:{newValue:savedSlug}},'local'));}},onChanged:{addListener:fn=>listeners.push(fn)}}};`;
  res.end(`<!doctype html><html><head><title>LinkedIn fixture</title><style>main{font:16px system-ui}article,section{background:white;padding:30px;margin:20px;border-radius:12px}</style><style>${read('quiet.css')}</style>${kind==='css'?'':`<script>${read('policy.js')}</script><script>${shim}</script><script>${read('content.js')}</script>`}</head><body><header id="global-nav">Navigation</header><div><main>${content}</main><aside>Suggestions</aside></div><div class="msg-overlay-container" id="inbox">Messages</div>${after}<script>${fixtureScript}</script></body></html>`);
});
const port = Number(process.env.PORT || 8765);
server.listen(port,'127.0.0.1',()=>console.log(`Open http://127.0.0.1:${port} for browser fixture checks.`));
